# ============================================================================
# IDM Clone - CI/CD Build Pipeline
#
# Builds the IDM Clone project on Windows using Visual Studio 2022 (v143)
# and produces downloadable .exe artifacts for both x64 and Win32.
#
# Triggers: push to main/develop, pull requests, and manual dispatch
# ============================================================================

name: Build IDMClone

on:
  push:
    branches: [ main, develop, genspark_ai_developer ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

# Cancel in-progress runs for the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SOLUTION_FILE: IDMClone.sln
  BUILD_CONFIGURATION: ${{ github.event.inputs.configuration || 'Release' }}

jobs:
  # ===========================================================================
  # BUILD JOB - Compiles for both x64 and Win32
  # ===========================================================================
  build:
    name: Build ${{ matrix.platform }} ${{ github.event.inputs.configuration || 'Release' }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform: [x64, Win32]

    steps:
      # ── Checkout ──────────────────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── Setup MSBuild ────────────────────────────────────────────────────
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,)'

      # ── Install MFC Component ────────────────────────────────────────────
      # MFC is required but not always pre-installed on GitHub runners
      - name: Ensure MFC is available
        shell: cmd
        run: |
          echo Checking for MFC headers...
          where /r "C:\Program Files\Microsoft Visual Studio" afxwin.h 2>nul
          if %ERRORLEVEL% NEQ 0 (
            echo MFC not found - attempting to install...
            "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify ^
              --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" ^
              --add Microsoft.VisualStudio.Component.VC.ATLMFC ^
              --quiet --norestart --wait 2>nul
          ) else (
            echo MFC headers found.
          )

      # ── Restore NuGet packages (if any) ──────────────────────────────────
      - name: Restore NuGet packages
        shell: cmd
        run: |
          if exist packages.config (
            nuget restore %SOLUTION_FILE%
          ) else (
            echo No NuGet packages to restore.
          )

      # ── Build Solution ───────────────────────────────────────────────────
      - name: Build ${{ matrix.platform }} ${{ env.BUILD_CONFIGURATION }}
        shell: cmd
        run: |
          msbuild %SOLUTION_FILE% ^
            /p:Configuration=%BUILD_CONFIGURATION% ^
            /p:Platform=${{ matrix.platform }} ^
            /m ^
            /verbosity:minimal ^
            /p:WarningLevel=3

      # ── Verify Output ────────────────────────────────────────────────────
      - name: Verify build output
        shell: cmd
        run: |
          echo === Build Output ===
          dir /s /b "bin\${{ matrix.platform }}\%BUILD_CONFIGURATION%\IDMClone.exe" 2>nul
          if %ERRORLEVEL% NEQ 0 (
            echo ERROR: IDMClone.exe not found!
            exit /b 1
          )
          echo.
          echo === Extension Files ===
          dir /s /b "bin\${{ matrix.platform }}\%BUILD_CONFIGURATION%\extension\*.*" 2>nul
          echo.
          echo Build successful!

      # ── Upload Artifacts ─────────────────────────────────────────────────
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: IDMClone-${{ matrix.platform }}-${{ env.BUILD_CONFIGURATION }}
          path: |
            bin/${{ matrix.platform }}/${{ env.BUILD_CONFIGURATION }}/IDMClone.exe
            bin/${{ matrix.platform }}/${{ env.BUILD_CONFIGURATION }}/extension/**
          if-no-files-found: error
          retention-days: 30

  # ===========================================================================
  # CMAKE BUILD JOB - Validates CMake build system works
  # ===========================================================================
  cmake-build:
    name: CMake Build (x64 Release)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.0,)'

      - name: Ensure MFC is available
        shell: cmd
        run: |
          where /r "C:\Program Files\Microsoft Visual Studio" afxwin.h 2>nul
          if %ERRORLEVEL% NEQ 0 (
            "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify ^
              --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" ^
              --add Microsoft.VisualStudio.Component.VC.ATLMFC ^
              --quiet --norestart --wait 2>nul
          )

      - name: Configure CMake
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..

      - name: Build with CMake
        shell: cmd
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Verify CMake output
        shell: cmd
        run: |
          dir /s /b "build\bin\Release\IDMClone.exe" 2>nul
          if %ERRORLEVEL% NEQ 0 (
            echo ERROR: CMake build output not found!
            exit /b 1
          )
          echo CMake build successful!

  # ===========================================================================
  # RELEASE JOB - Creates GitHub Release on tags
  # ===========================================================================
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: IDMClone-x64-Release
          path: release/x64

      - name: Download Win32 artifact
        uses: actions/download-artifact@v4
        with:
          name: IDMClone-Win32-Release
          path: release/Win32

      - name: Package artifacts
        run: |
          cd release/x64 && zip -r ../../IDMClone-x64.zip . && cd ../..
          cd release/Win32 && zip -r ../../IDMClone-Win32.zip . && cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            IDMClone-x64.zip
            IDMClone-Win32.zip
          generate_release_notes: true
